[package]
name = "versed"
version = "0.0.1"
edition = "2024"

[dependencies]
anstream = "0.6.20"
anstyle = "1.0.11"
ariadne = "0.5.1"
chumsky = "0.10.1"
clap = { version = "4.5.43", features = ["derive"] }
icu_properties = "2.0.1"
thiserror = "2.0.12"
